In [1]:
import numpy as np
import pandas as pd
from sklearn import linear_model

In [2]:
df = pd.read_csv('Data.csv', sep='\t' )
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

In [28]:
import math
median_bedrooms = math.floor(df.bedrooms.median())
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       3.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

In [9]:
# fill a specific column
df.bedrooms.fillna(value=median_bedrooms, inplace=True)

In [10]:
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       3.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

# fit the model

In [12]:
reg = linear_model.LinearRegression()
reg.fit(df[['area','bedrooms','age']],df.price)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [15]:
# print the coeficient and intercept in the following equation
# price = a1 * area + a2 * bedrooms + a3 * age + b
print (reg.coef_)
print (reg.intercept_)

[   137.25 -26025.    -6825.  ]
383724.9999999998


In [16]:
reg.predict([[3000,3,40]])

array([444400.])

# train on another dataset

In [42]:
ass_df = pd.read_csv('aa.csv', delimiter='\t')
ass_df

experience  test_score  interview_score  salary
0        NaN         8.0                9   50000
1        NaN         8.0                6   45000
2       five         6.0                7   60000
3        two        10.0               10   65000
4      seven         9.0                6   70000
5      three         7.0               10   62000
6        ten         NaN                7   72000
7     eleven         7.0                8   80000

In [44]:
                                          # preprocessing of the data

# test_score column
test_score_median = ass_df['test_score'].median()
ass_df.test_score = ass_df.test_score.fillna(value=test_score_median)
ass_df

# experience column


In [50]:
ass_df.experience = [0,0,5,2,7,3,10,11]

In [52]:
experience_median = ass_df['experience'].median()

In [56]:
ass_df.experience = ass_df.experience.replace(to_replace=0,value=experience_median) 

In [57]:
ass_df

experience  test_score  interview_score  salary
0           4         8.0                9   50000
1           4         8.0                6   45000
2           5         6.0                7   60000
3           2        10.0               10   65000
4           7         9.0                6   70000
5           3         7.0               10   62000
6          10         8.0                7   72000
7          11         7.0                8   80000

In [58]:
reg_tst = linear_model.LinearRegression()
reg_tst.fit(ass_df[['experience', 'test_score', 'interview_score']], ass_df.salary)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [62]:
# print the coeficient and intercept in the following equation
# price = a1 * area + a2 * bedrooms + a3 * age + b
print (reg_tst.coef_)
print (reg_tst.intercept_)

[3390.87422644 1803.45158198 3184.69450013]
4220.8228013597545


In [65]:
reg_tst.predict([[10,8.0,7]])

array([74850.03922252])